/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'psadmin' at '16/09/27 11:19' with Gradle 2.3
 *
 * @author psadmin, @date 16/09/27 11:19
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
