cacti-cli -f node/Db2/CAPA_D1-MMDB-0  --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-MMDB-1  --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-MMDB-2  --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-MMDB    --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-SMDB0-0 --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-SMDB1-0 --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-URADB-0 --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-URADB-1 --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-URADB-2 --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-URADB   --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-RTDDB-0 --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-RTDDB-1 --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-RTDDB-2 --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-RTDDB   --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-SCHDB-0 --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-SCHDB-1 --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-SCHDB-2 --device-sort natural
cacti-cli -f node/Db2/CAPA_D1-SCHDB   --device-sort natural
