#!/bin/bash
source /home/oracle/.profile_orcl
export ORACLE_SID=orcl
sqlplus -s perfstat/perfstat <<EOF
DELETE FROM SHARED_POOL_USED_HIST
WHERE "DATE" < SYSDATE -3;
COMMIT;

INSERT INTO SHARED_POOL_USED_HIST
SELECT * FROM (
SELECT SYSDATE AS "DATE",
PLAN_HASH_VALUE,
COUNT(SQL_ID) AS SQL_COUNT,
SUM(SHARABLE_MEM) AS SUM_SHARABLE_MEM,
SUM(VERSION_COUNT) AS SUM_VERSION_COUNT,
  SUM(LENGTH(SQL_FULLTEXT)) AS SUM_SQL_LENGTH,
  ROUND(SUM(LENGTH(SQL_FULLTEXT))/COUNT(SQL_ID)) AS AVG_SQL_LENGTH
  FROM V\$SQLAREA
GROUP BY PLAN_HASH_VALUE
ORDER BY 4 DESC)
WHERE ROWNUM < 31;
COMMIT;

DELETE FROM SHARED_POOL_USED_SQL
WHERE "DATE" < SYSDATE -30;
COMMIT;

INSERT INTO SHARED_POOL_USED_SQL
SELECT "DATE",SQL_ID,PLAN_HASH_VALUE,SQL_TEXT FROM
(SELECT A."DATE",A.PLAN_HASH_VALUE,B.SQL_ID,RANK() OVER (PARTITION BY A.PLAN_HASH_VALUE ORDER BY LENGTH(B.SQL_TEXT) DESC) AS "RANK",B.SQL_TEXT
FROM
(SELECT DISTINCT A."DATE",B.PLAN_HASH_VALUE,B.SQL_ID FROM
SHARED_POOL_USED_HIST A,DBA_HIST_SQLSTAT B
WHERE A."DATE" = (SELECT MAX("DATE") FROM SHARED_POOL_USED_HIST)
AND B.PLAN_HASH_VALUE = A.PLAN_HASH_VALUE
AND B.PLAN_HASH_VALUE<>0) A,DBA_HIST_SQLTEXT B
WHERE A.SQL_ID = B.SQL_ID)
WHERE "RANK" = 1;
COMMIT;
EOF
