requires 'Class::Accessor::Fast';
requires 'Crypt::Blowfish';
requires 'Crypt::CBC';
requires 'Daemon::Control';
requires 'DBI';
requires 'Digest::SHA1';
requires 'Readonly';
requires 'Encode';
requires 'Expect';
requires 'Storable';
requires 'File::Copy::Recursive';
requires 'File::Path';
requires 'File::Path::Tiny';
requires 'Filesys::Notify::Simple';
requires 'Getopt::Long';
requires 'Git::Repository';
requires 'IO::CaptureOutput';
requires 'JSON::XS';
requires 'Hash::Merge::Simple';
requires 'Log::Handler';
requires 'Log::Handler::Output::File::Stamper';
requires 'Net::Graphite';
requires 'Text::Markdown::Discount';
requires 'Object::Container';
requires 'Object::Container::Exporter';
requires 'Path::Class';
requires 'Rex::Commands';
requires 'Rex::Commands::File';
requires 'Rex::Commands::Fs';
requires 'Rex::Commands::Run';
#requires 'SOAP::Lite';
requires 'Socket';
requires 'String::CamelCase';
requires 'Template';
requires 'Test::More';
requires 'Text::Patch';
requires 'Time::HiRes';
requires 'Time::Local';
requires 'Time::Moment';
requires 'Time::Piece', '>= 1.30';
requires 'Time::Seconds';
requires 'YAML::Tiny';
requires 'Zabbix::API';
requires 'JSON::RPC';
requires 'parent';
requires 'perl', '5.008_005';

on configure => sub {
#    requires 'Module::Build::Tiny', '0.038';
    requires 'Module::Build', '0.038';
    requires 'perl', '5.008005';
};

on test => sub {
#    requires 'JSON';
#    requires 'MIME::Entity';
#    requires 'SOAP::Lite::Packager';
	requires 'Devel::NYTProf';
};
