/* soapStub.h
   Generated by gSOAP 2.8.51 for GetperfServiceSoapcpp2.h

gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef GETPERF_GETPERF_SERVICE_SOAPCPP2_H
#define GETPERF_GETPERF_SERVICE_SOAPCPP2_H
#endif

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20851
# error "GSOAP VERSION 20851 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Structs and Unions                                                         *
 *                                                                            *
\******************************************************************************/

struct ns1__sendEventLogResponse;	/* GetperfServiceSoapcpp2.h:36 */
struct ns1__sendEventLog;	/* GetperfServiceSoapcpp2.h:36 */
struct ns1__getPerfConfigFileResponse;	/* GetperfServiceSoapcpp2.h:46 */
struct ns1__getPerfConfigFile;	/* GetperfServiceSoapcpp2.h:46 */
struct ns1__reserveSendPerfDataResponse;	/* GetperfServiceSoapcpp2.h:56 */
struct ns1__reserveSendPerfData;	/* GetperfServiceSoapcpp2.h:56 */
struct ns1__sendPerfDataResponse;	/* GetperfServiceSoapcpp2.h:66 */
struct ns1__sendPerfData;	/* GetperfServiceSoapcpp2.h:66 */
struct ns1__reserveSenderResponse;	/* GetperfServiceSoapcpp2.h:76 */
struct ns1__reserveSender;	/* GetperfServiceSoapcpp2.h:76 */
struct ns1__sendDataResponse;	/* GetperfServiceSoapcpp2.h:85 */
struct ns1__sendData;	/* GetperfServiceSoapcpp2.h:85 */
struct ns1__downloadCertificateResponse;	/* GetperfServiceSoapcpp2.h:95 */
struct ns1__downloadCertificate;	/* GetperfServiceSoapcpp2.h:95 */
struct ns1__sendMessageResponse;	/* GetperfServiceSoapcpp2.h:106 */
struct ns1__sendMessage;	/* GetperfServiceSoapcpp2.h:106 */
struct ns2__checkAgentResponse;	/* GetperfServiceSoapcpp2.h:120 */
struct ns2__checkAgent;	/* GetperfServiceSoapcpp2.h:120 */
struct ns2__registAgentResponse;	/* GetperfServiceSoapcpp2.h:130 */
struct ns2__registAgent;	/* GetperfServiceSoapcpp2.h:130 */
struct ns2__getLatestBuildResponse;	/* GetperfServiceSoapcpp2.h:139 */
struct ns2__getLatestBuild;	/* GetperfServiceSoapcpp2.h:139 */
struct ns2__downloadUpdateModuleResponse;	/* GetperfServiceSoapcpp2.h:149 */
struct ns2__downloadUpdateModule;	/* GetperfServiceSoapcpp2.h:149 */

/* GetperfServiceSoapcpp2.h:36 */
#ifndef SOAP_TYPE_ns1__sendEventLogResponse
#define SOAP_TYPE_ns1__sendEventLogResponse (9)
/* complex XSD type 'ns1:sendEventLogResponse': */
struct ns1__sendEventLogResponse {
        /** Optional element 'sendEventLogReturn' of XSD type 'xsd:string' */
        char **_sendEventLogReturn;
};
#endif

/* GetperfServiceSoapcpp2.h:36 */
#ifndef SOAP_TYPE_ns1__sendEventLog
#define SOAP_TYPE_ns1__sendEventLog (10)
/* complex XSD type 'ns1:sendEventLog': */
struct ns1__sendEventLog {
        /** Optional element 'siteKey' of XSD type 'xsd:string' */
        char *_siteKey;
        /** Optional element 'hostname' of XSD type 'xsd:string' */
        char *_hostname;
        /** Optional element 'lvl' of XSD type 'xsd:string' */
        char *_lvl;
        /** Optional element 'msg' of XSD type 'xsd:string' */
        char *_msg;
};
#endif

/* GetperfServiceSoapcpp2.h:46 */
#ifndef SOAP_TYPE_ns1__getPerfConfigFileResponse
#define SOAP_TYPE_ns1__getPerfConfigFileResponse (12)
/* complex XSD type 'ns1:getPerfConfigFileResponse': */
struct ns1__getPerfConfigFileResponse {
        /** Optional element 'getPerfConfigFileReturn' of XSD type 'xsd:string' */
        char **_getPerfConfigFileReturn;
};
#endif

/* GetperfServiceSoapcpp2.h:46 */
#ifndef SOAP_TYPE_ns1__getPerfConfigFile
#define SOAP_TYPE_ns1__getPerfConfigFile (13)
/* complex XSD type 'ns1:getPerfConfigFile': */
struct ns1__getPerfConfigFile {
        /** Optional element 'siteKey' of XSD type 'xsd:string' */
        char *_siteKey;
        /** Optional element 'hostname' of XSD type 'xsd:string' */
        char *_hostname;
        /** Optional element 'fileName' of XSD type 'xsd:string' */
        char *_fileName;
};
#endif

/* GetperfServiceSoapcpp2.h:56 */
#ifndef SOAP_TYPE_ns1__reserveSendPerfDataResponse
#define SOAP_TYPE_ns1__reserveSendPerfDataResponse (15)
/* complex XSD type 'ns1:reserveSendPerfDataResponse': */
struct ns1__reserveSendPerfDataResponse {
        /** Optional element 'reserveSendPerfDataReturn' of XSD type 'xsd:string' */
        char **_reserveSendPerfDataReturn;
};
#endif

/* GetperfServiceSoapcpp2.h:56 */
#ifndef SOAP_TYPE_ns1__reserveSendPerfData
#define SOAP_TYPE_ns1__reserveSendPerfData (16)
/* complex XSD type 'ns1:reserveSendPerfData': */
struct ns1__reserveSendPerfData {
        /** Optional element 'siteKey' of XSD type 'xsd:string' */
        char *_siteKey;
        /** Optional element 'hostname' of XSD type 'xsd:string' */
        char *_hostname;
        /** Optional element 'onOff' of XSD type 'xsd:string' */
        char *_onOff;
};
#endif

/* GetperfServiceSoapcpp2.h:66 */
#ifndef SOAP_TYPE_ns1__sendPerfDataResponse
#define SOAP_TYPE_ns1__sendPerfDataResponse (18)
/* complex XSD type 'ns1:sendPerfDataResponse': */
struct ns1__sendPerfDataResponse {
        /** Optional element 'sendPerfData' of XSD type 'xsd:string' */
        char **_sendPerfData;
};
#endif

/* GetperfServiceSoapcpp2.h:66 */
#ifndef SOAP_TYPE_ns1__sendPerfData
#define SOAP_TYPE_ns1__sendPerfData (19)
/* complex XSD type 'ns1:sendPerfData': */
struct ns1__sendPerfData {
        /** Optional element 'siteKey' of XSD type 'xsd:string' */
        char *_siteKey;
        /** Optional element 'hostname' of XSD type 'xsd:string' */
        char *_hostname;
        /** Optional element 'fileName' of XSD type 'xsd:string' */
        char *_fileName;
};
#endif

/* GetperfServiceSoapcpp2.h:76 */
#ifndef SOAP_TYPE_ns1__reserveSenderResponse
#define SOAP_TYPE_ns1__reserveSenderResponse (22)
/* complex XSD type 'ns1:reserveSenderResponse': */
struct ns1__reserveSenderResponse {
        /** Optional element 'reserveSenderReturn' of XSD type 'xsd:string' */
        char **_reserveSenderReturn;
};
#endif

/* GetperfServiceSoapcpp2.h:76 */
#ifndef SOAP_TYPE_ns1__reserveSender
#define SOAP_TYPE_ns1__reserveSender (23)
/* complex XSD type 'ns1:reserveSender': */
struct ns1__reserveSender {
        /** Optional element 'siteKey' of XSD type 'xsd:string' */
        char *_siteKey;
        /** Optional element 'hostname' of XSD type 'xsd:string' */
        char *_hostname;
        /** Optional element 'fileSize' of XSD type 'xsd:int' */
        int *_fileSize;
};
#endif

/* GetperfServiceSoapcpp2.h:85 */
#ifndef SOAP_TYPE_ns1__sendDataResponse
#define SOAP_TYPE_ns1__sendDataResponse (25)
/* complex XSD type 'ns1:sendDataResponse': */
struct ns1__sendDataResponse {
        /** Optional element 'sendDataReturn' of XSD type 'xsd:string' */
        char **_sendDataReturn;
};
#endif

/* GetperfServiceSoapcpp2.h:85 */
#ifndef SOAP_TYPE_ns1__sendData
#define SOAP_TYPE_ns1__sendData (26)
/* complex XSD type 'ns1:sendData': */
struct ns1__sendData {
        /** Optional element 'siteKey' of XSD type 'xsd:string' */
        char *_siteKey;
        /** Optional element 'hostname' of XSD type 'xsd:string' */
        char *_hostname;
};
#endif

/* GetperfServiceSoapcpp2.h:95 */
#ifndef SOAP_TYPE_ns1__downloadCertificateResponse
#define SOAP_TYPE_ns1__downloadCertificateResponse (30)
/* complex XSD type 'ns1:downloadCertificateResponse': */
struct ns1__downloadCertificateResponse {
        /** Optional element 'downloadCertificateReturn' of XSD type 'xsd:string' */
        char **_downloadCertificateReturn;
};
#endif

/* GetperfServiceSoapcpp2.h:95 */
#ifndef SOAP_TYPE_ns1__downloadCertificate
#define SOAP_TYPE_ns1__downloadCertificate (31)
/* complex XSD type 'ns1:downloadCertificate': */
struct ns1__downloadCertificate {
        /** Optional element 'siteKey' of XSD type 'xsd:string' */
        char *_siteKey;
        /** Optional element 'hostname' of XSD type 'xsd:string' */
        char *_hostname;
        /** Optional element 'timestamp' of XSD type 'xsd:long' */
        long *_timestamp;
};
#endif

/* GetperfServiceSoapcpp2.h:106 */
#ifndef SOAP_TYPE_ns1__sendMessageResponse
#define SOAP_TYPE_ns1__sendMessageResponse (33)
/* complex XSD type 'ns1:sendMessageResponse': */
struct ns1__sendMessageResponse {
        /** Optional element 'sendMessageReturn' of XSD type 'xsd:string' */
        char **_sendMessageReturn;
};
#endif

/* GetperfServiceSoapcpp2.h:106 */
#ifndef SOAP_TYPE_ns1__sendMessage
#define SOAP_TYPE_ns1__sendMessage (34)
/* complex XSD type 'ns1:sendMessage': */
struct ns1__sendMessage {
        /** Optional element 'siteKey' of XSD type 'xsd:string' */
        char *_siteKey;
        /** Optional element 'hostname' of XSD type 'xsd:string' */
        char *_hostname;
        /** Optional element 'sererity' of XSD type 'xsd:int' */
        int *_sererity;
        /** Optional element 'msg' of XSD type 'xsd:string' */
        char *_msg;
};
#endif

/* GetperfServiceSoapcpp2.h:120 */
#ifndef SOAP_TYPE_ns2__checkAgentResponse
#define SOAP_TYPE_ns2__checkAgentResponse (36)
/* complex XSD type 'ns2:checkAgentResponse': */
struct ns2__checkAgentResponse {
        /** Optional element 'checkAgentReturn' of XSD type 'xsd:string' */
        char **_checkAgentReturn;
};
#endif

/* GetperfServiceSoapcpp2.h:120 */
#ifndef SOAP_TYPE_ns2__checkAgent
#define SOAP_TYPE_ns2__checkAgent (37)
/* complex XSD type 'ns2:checkAgent': */
struct ns2__checkAgent {
        /** Optional element 'siteKey' of XSD type 'xsd:string' */
        char *_siteKey;
        /** Optional element 'hostname' of XSD type 'xsd:string' */
        char *_hostname;
        /** Optional element 'accessKey' of XSD type 'xsd:string' */
        char *_accessKey;
};
#endif

/* GetperfServiceSoapcpp2.h:130 */
#ifndef SOAP_TYPE_ns2__registAgentResponse
#define SOAP_TYPE_ns2__registAgentResponse (39)
/* complex XSD type 'ns2:registAgentResponse': */
struct ns2__registAgentResponse {
        /** Optional element 'registAgentReturn' of XSD type 'xsd:string' */
        char **_registAgentReturn;
};
#endif

/* GetperfServiceSoapcpp2.h:130 */
#ifndef SOAP_TYPE_ns2__registAgent
#define SOAP_TYPE_ns2__registAgent (40)
/* complex XSD type 'ns2:registAgent': */
struct ns2__registAgent {
        /** Optional element 'siteKey' of XSD type 'xsd:string' */
        char *_siteKey;
        /** Optional element 'hostname' of XSD type 'xsd:string' */
        char *_hostname;
        /** Optional element 'accessKey' of XSD type 'xsd:string' */
        char *_accessKey;
};
#endif

/* GetperfServiceSoapcpp2.h:139 */
#ifndef SOAP_TYPE_ns2__getLatestBuildResponse
#define SOAP_TYPE_ns2__getLatestBuildResponse (42)
/* complex XSD type 'ns2:getLatestBuildResponse': */
struct ns2__getLatestBuildResponse {
        /** Optional element 'getLatestBuildReturn' of XSD type 'xsd:string' */
        char **_getLatestBuildReturn;
};
#endif

/* GetperfServiceSoapcpp2.h:139 */
#ifndef SOAP_TYPE_ns2__getLatestBuild
#define SOAP_TYPE_ns2__getLatestBuild (43)
/* complex XSD type 'ns2:getLatestBuild': */
struct ns2__getLatestBuild {
        /** Optional element 'moduleTag' of XSD type 'xsd:string' */
        char *_moduleTag;
        /** Optional element 'majorVer' of XSD type 'xsd:int' */
        int *_majorVer;
};
#endif

/* GetperfServiceSoapcpp2.h:149 */
#ifndef SOAP_TYPE_ns2__downloadUpdateModuleResponse
#define SOAP_TYPE_ns2__downloadUpdateModuleResponse (45)
/* complex XSD type 'ns2:downloadUpdateModuleResponse': */
struct ns2__downloadUpdateModuleResponse {
        /** Optional element 'downloadUpdateModuleReturn' of XSD type 'xsd:string' */
        char **_downloadUpdateModuleReturn;
};
#endif

/* GetperfServiceSoapcpp2.h:149 */
#ifndef SOAP_TYPE_ns2__downloadUpdateModule
#define SOAP_TYPE_ns2__downloadUpdateModule (46)
/* complex XSD type 'ns2:downloadUpdateModule': */
struct ns2__downloadUpdateModule {
        /** Optional element 'moduleTag' of XSD type 'xsd:string' */
        char *_moduleTag;
        /** Optional element 'majorVer' of XSD type 'xsd:int' */
        int *_majorVer;
        /** Optional element 'build' of XSD type 'xsd:int' */
        int *_build;
};
#endif

/* GetperfServiceSoapcpp2.h:152 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (47)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* empty struct is a GNU extension */
#endif
};
#endif
#endif

/* GetperfServiceSoapcpp2.h:152 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (48)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
        /** Optional element 'SOAP-ENV:Value' of XSD type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
};
#endif
#endif

/* GetperfServiceSoapcpp2.h:152 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (50)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
};
#endif
#endif

/* GetperfServiceSoapcpp2.h:152 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (53)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
        /** Optional element 'SOAP-ENV:Text' of XSD type 'xsd:string' */
        char *SOAP_ENV__Text;
};
#endif
#endif

/* GetperfServiceSoapcpp2.h:152 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (54)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
        /** Optional element 'faultcode' of XSD type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XSD type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XSD type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XSD type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XSD type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XSD type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* GetperfServiceSoapcpp2.h:21 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* GetperfServiceSoapcpp2.h:21 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* long has binding name 'long' for type 'xsd:long' */
#ifndef SOAP_TYPE_long
#define SOAP_TYPE_long (27)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (54)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (53)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (50)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (48)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (47)
#endif

/* struct ns2__downloadUpdateModule has binding name 'ns2__downloadUpdateModule' for type 'ns2:downloadUpdateModule' */
#ifndef SOAP_TYPE_ns2__downloadUpdateModule
#define SOAP_TYPE_ns2__downloadUpdateModule (46)
#endif

/* struct ns2__downloadUpdateModuleResponse has binding name 'ns2__downloadUpdateModuleResponse' for type 'ns2:downloadUpdateModuleResponse' */
#ifndef SOAP_TYPE_ns2__downloadUpdateModuleResponse
#define SOAP_TYPE_ns2__downloadUpdateModuleResponse (45)
#endif

/* struct ns2__getLatestBuild has binding name 'ns2__getLatestBuild' for type 'ns2:getLatestBuild' */
#ifndef SOAP_TYPE_ns2__getLatestBuild
#define SOAP_TYPE_ns2__getLatestBuild (43)
#endif

/* struct ns2__getLatestBuildResponse has binding name 'ns2__getLatestBuildResponse' for type 'ns2:getLatestBuildResponse' */
#ifndef SOAP_TYPE_ns2__getLatestBuildResponse
#define SOAP_TYPE_ns2__getLatestBuildResponse (42)
#endif

/* struct ns2__registAgent has binding name 'ns2__registAgent' for type 'ns2:registAgent' */
#ifndef SOAP_TYPE_ns2__registAgent
#define SOAP_TYPE_ns2__registAgent (40)
#endif

/* struct ns2__registAgentResponse has binding name 'ns2__registAgentResponse' for type 'ns2:registAgentResponse' */
#ifndef SOAP_TYPE_ns2__registAgentResponse
#define SOAP_TYPE_ns2__registAgentResponse (39)
#endif

/* struct ns2__checkAgent has binding name 'ns2__checkAgent' for type 'ns2:checkAgent' */
#ifndef SOAP_TYPE_ns2__checkAgent
#define SOAP_TYPE_ns2__checkAgent (37)
#endif

/* struct ns2__checkAgentResponse has binding name 'ns2__checkAgentResponse' for type 'ns2:checkAgentResponse' */
#ifndef SOAP_TYPE_ns2__checkAgentResponse
#define SOAP_TYPE_ns2__checkAgentResponse (36)
#endif

/* struct ns1__sendMessage has binding name 'ns1__sendMessage' for type 'ns1:sendMessage' */
#ifndef SOAP_TYPE_ns1__sendMessage
#define SOAP_TYPE_ns1__sendMessage (34)
#endif

/* struct ns1__sendMessageResponse has binding name 'ns1__sendMessageResponse' for type 'ns1:sendMessageResponse' */
#ifndef SOAP_TYPE_ns1__sendMessageResponse
#define SOAP_TYPE_ns1__sendMessageResponse (33)
#endif

/* struct ns1__downloadCertificate has binding name 'ns1__downloadCertificate' for type 'ns1:downloadCertificate' */
#ifndef SOAP_TYPE_ns1__downloadCertificate
#define SOAP_TYPE_ns1__downloadCertificate (31)
#endif

/* struct ns1__downloadCertificateResponse has binding name 'ns1__downloadCertificateResponse' for type 'ns1:downloadCertificateResponse' */
#ifndef SOAP_TYPE_ns1__downloadCertificateResponse
#define SOAP_TYPE_ns1__downloadCertificateResponse (30)
#endif

/* struct ns1__sendData has binding name 'ns1__sendData' for type 'ns1:sendData' */
#ifndef SOAP_TYPE_ns1__sendData
#define SOAP_TYPE_ns1__sendData (26)
#endif

/* struct ns1__sendDataResponse has binding name 'ns1__sendDataResponse' for type 'ns1:sendDataResponse' */
#ifndef SOAP_TYPE_ns1__sendDataResponse
#define SOAP_TYPE_ns1__sendDataResponse (25)
#endif

/* struct ns1__reserveSender has binding name 'ns1__reserveSender' for type 'ns1:reserveSender' */
#ifndef SOAP_TYPE_ns1__reserveSender
#define SOAP_TYPE_ns1__reserveSender (23)
#endif

/* struct ns1__reserveSenderResponse has binding name 'ns1__reserveSenderResponse' for type 'ns1:reserveSenderResponse' */
#ifndef SOAP_TYPE_ns1__reserveSenderResponse
#define SOAP_TYPE_ns1__reserveSenderResponse (22)
#endif

/* struct ns1__sendPerfData has binding name 'ns1__sendPerfData' for type 'ns1:sendPerfData' */
#ifndef SOAP_TYPE_ns1__sendPerfData
#define SOAP_TYPE_ns1__sendPerfData (19)
#endif

/* struct ns1__sendPerfDataResponse has binding name 'ns1__sendPerfDataResponse' for type 'ns1:sendPerfDataResponse' */
#ifndef SOAP_TYPE_ns1__sendPerfDataResponse
#define SOAP_TYPE_ns1__sendPerfDataResponse (18)
#endif

/* struct ns1__reserveSendPerfData has binding name 'ns1__reserveSendPerfData' for type 'ns1:reserveSendPerfData' */
#ifndef SOAP_TYPE_ns1__reserveSendPerfData
#define SOAP_TYPE_ns1__reserveSendPerfData (16)
#endif

/* struct ns1__reserveSendPerfDataResponse has binding name 'ns1__reserveSendPerfDataResponse' for type 'ns1:reserveSendPerfDataResponse' */
#ifndef SOAP_TYPE_ns1__reserveSendPerfDataResponse
#define SOAP_TYPE_ns1__reserveSendPerfDataResponse (15)
#endif

/* struct ns1__getPerfConfigFile has binding name 'ns1__getPerfConfigFile' for type 'ns1:getPerfConfigFile' */
#ifndef SOAP_TYPE_ns1__getPerfConfigFile
#define SOAP_TYPE_ns1__getPerfConfigFile (13)
#endif

/* struct ns1__getPerfConfigFileResponse has binding name 'ns1__getPerfConfigFileResponse' for type 'ns1:getPerfConfigFileResponse' */
#ifndef SOAP_TYPE_ns1__getPerfConfigFileResponse
#define SOAP_TYPE_ns1__getPerfConfigFileResponse (12)
#endif

/* struct ns1__sendEventLog has binding name 'ns1__sendEventLog' for type 'ns1:sendEventLog' */
#ifndef SOAP_TYPE_ns1__sendEventLog
#define SOAP_TYPE_ns1__sendEventLog (10)
#endif

/* struct ns1__sendEventLogResponse has binding name 'ns1__sendEventLogResponse' for type 'ns1:sendEventLogResponse' */
#ifndef SOAP_TYPE_ns1__sendEventLogResponse
#define SOAP_TYPE_ns1__sendEventLogResponse (9)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (56)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (55)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (49)
#endif

/* long * has binding name 'PointerTolong' for type 'xsd:long' */
#ifndef SOAP_TYPE_PointerTolong
#define SOAP_TYPE_PointerTolong (28)
#endif

/* int * has binding name 'PointerToint' for type 'xsd:int' */
#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (20)
#endif

/* char ** has binding name 'PointerTostring' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (7)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stub Functions                                            *
 *                                                                            *
\******************************************************************************/

    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__sendEventLog(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_siteKey, char *_hostname, char *_lvl, char *_msg, char **_sendEventLogReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__getPerfConfigFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_siteKey, char *_hostname, char *_fileName, char **_getPerfConfigFileReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__reserveSendPerfData(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_siteKey, char *_hostname, char *_onOff, char **_reserveSendPerfDataReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__sendPerfData(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_siteKey, char *_hostname, char *_fileName, char **_sendPerfData);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__reserveSender(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_siteKey, char *_hostname, int *_fileSize, char **_reserveSenderReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__sendData(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_siteKey, char *_hostname, char **_sendDataReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__downloadCertificate(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_siteKey, char *_hostname, long *_timestamp, char **_downloadCertificateReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__sendMessage(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_siteKey, char *_hostname, int *_sererity, char *_msg, char **_sendMessageReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__checkAgent(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_siteKey, char *_hostname, char *_accessKey, char **_checkAgentReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__registAgent(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_siteKey, char *_hostname, char *_accessKey, char **_registAgentReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getLatestBuild(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_moduleTag, int *_majorVer, char **_getLatestBuildReturn);
    SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__downloadUpdateModule(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *_moduleTag, int *_majorVer, int *_build, char **_downloadUpdateModuleReturn);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
