SELECT CURRENT TIMESTAMP AS TIMESTAMP,
VARCHAR(S.INDSCHEMA) AS INDSCHEMA,
VARCHAR(S.INDNAME) AS INDNAME,T.*
FROM TABLE(MON_GET_INDEX('', '', -2)) AS T, SYSCAT.INDEXES AS S
WHERE T.TABSCHEMA = S.TABSCHEMA AND
T.TABNAME = S.TABNAME AND
T.IID = S.IID
;
