SELECT 
    STMTID, 
    TO_CHAR(LAST_METRICS_UPDATE, 'YYYY-MM-DD HH24:MI:SS') AS LAST_METRICS_UPDATE,
    cast(STMT_TEXT as varchar(10240)) AS STMT_TEXT
FROM 
    TABLE(MON_GET_PKG_CACHE_STMT( NULL, NULL, NULL, -2))
--WHERE 
--    NUM_EXEC_WITH_METRICS <> 0
--AND
--    LAST_METRICS_UPDATE >= CURRENT TIMESTAMP - 15 minutes
ORDER BY
    STMTID,
    LAST_METRICS_UPDATE
WITH UR
;

