SELECT MON_GET_DATABASE.METRIC_TIMESTAMP, MON_GET_DATABASE.DB_NAME, MON_GET_DATABASE.MEMBER, MON_GET_DATABASE.APPLS_CUR_CONS
FROM SMC_V111.MON_GET_DATABASE MON_GET_DATABASE
WHERE (MON_GET_DATABASE.METRIC_TIMESTAMP>={ts '2019-08-01 00:00:00'})
ORDER BY MON_GET_DATABASE.METRIC_TIMESTAMP, MON_GET_DATABASE.DB_NAME, MON_GET_DATABASE.MEMBER
;
