SELECT MON_GET_DATABASE_S.DB_NAME, MON_GET_DATABASE_S.METRIC_TIMESTAMP, MON_GET_DATABASE_S.MEMBER, MON_GET_DATABASE_S.LOCK_LIST_IN_USE, MON_GET_DATABASE_S.DEADLOCKS, MON_GET_DATABASE_S.LOCK_ESCALS, MON_GET_DATABASE_S.LOCK_TIMEOUTS, MON_GET_DATABASE_S.LOCK_WAIT_TIME, MON_GET_DATABASE_S.LOCK_WAITS, MON_GET_DATABASE_S.LOCK_WAITS_GLOBAL, MON_GET_DATABASE_S.LOCK_WAIT_TIME_GLOBAL, MON_GET_DATABASE_S.LOCK_TIMEOUTS_GLOBAL, MON_GET_DATABASE_S.LOCK_ESCALS_MAXLOCKS, MON_GET_DATABASE_S.LOCK_ESCALS_LOCKLIST, MON_GET_DATABASE_S.LOCK_ESCALS_GLOBAL
FROM SMC_V111.MON_GET_DATABASE_S MON_GET_DATABASE_S
WHERE (MON_GET_DATABASE_S.METRIC_TIMESTAMP>={ts '2019-08-01 00:00:00'})
ORDER BY MON_GET_DATABASE_S.METRIC_TIMESTAMP, MON_GET_DATABASE_S.DB_NAME, MON_GET_DATABASE_S.MEMBER
;
