cp ora_time_model_rac.json ../
cp ora_foreground_wait_rac.json ../
cp ora_event_Configuration.json ../
cp ora_event_Concurrency.json ../
cp ora_event_UserIO.json ../
cp ora_event_Scheduler.json ../
cp ora_event_NA.json ../
cp ora_event_Cluster.json ../
cp ora_event_SystemIO.json ../
cp ora_event_Commit.json ../
cp ora_event_Application.json ../
cp ora_event_Network.json ../
cp ora_event_Other.json ../
cp ora_event_Administrative.json ../
cp ora_background_event_SystemIO.json ../
cp ora_background_event_Commit.json ../
cp ora_background_event_Application.json ../
cp ora_background_event_Network.json ../
cp ora_background_event_Other.json ../
cp ora_background_event_Concurrency.json ../
cp ora_background_event_Configuration.json ../
cp ora_background_event_NA.json ../
cp ora_background_event_UserIO.json ../
cp ora_background_event_Cluster.json ../
cp ora_system_stat_rac.json ../
cp ora_interconnect_rac.json ../

