find ~/kit1/node/Oracle -name ora_time_model_rac.json
find ~/kit1/node/Oracle -name ora_foreground_wait_rac.json
find ~/kit1/node/Oracle -name ora_event_Configuration.json
find ~/kit1/node/Oracle -name ora_event_Concurrency.json
find ~/kit1/node/Oracle -name ora_event_UserIO.json
find ~/kit1/node/Oracle -name ora_event_Scheduler.json
find ~/kit1/node/Oracle -name ora_event_NA.json
find ~/kit1/node/Oracle -name ora_event_Cluster.json
find ~/kit1/node/Oracle -name ora_event_SystemIO.json
find ~/kit1/node/Oracle -name ora_event_Commit.json
find ~/kit1/node/Oracle -name ora_event_Application.json
find ~/kit1/node/Oracle -name ora_event_Network.json
find ~/kit1/node/Oracle -name ora_event_Other.json
find ~/kit1/node/Oracle -name ora_event_Administrative.json
find ~/kit1/node/Oracle -name ora_background_event_SystemIO.json
find ~/kit1/node/Oracle -name ora_background_event_Commit.json
find ~/kit1/node/Oracle -name ora_background_event_Application.json
find ~/kit1/node/Oracle -name ora_background_event_Network.json
find ~/kit1/node/Oracle -name ora_background_event_Other.json
find ~/kit1/node/Oracle -name ora_background_event_Concurrency.json
find ~/kit1/node/Oracle -name ora_background_event_Configuration.json
find ~/kit1/node/Oracle -name ora_background_event_NA.json
find ~/kit1/node/Oracle -name ora_background_event_UserIO.json
find ~/kit1/node/Oracle -name ora_background_event_Cluster.json
find ~/kit1/node/Oracle -name ora_system_stat_rac.json
find ~/kit1/node/Oracle -name ora_interconnect_rac.json

