COL VALUE FORMAT 999,999,999,999,999
COL DATE FORMAT A19

VARIABLE DBID NUMBER
VARIABLE BID NUMBER
VARIABLE EID NUMBER
VARIABLE BTIME VARCHAR2(20)
VARIABLE ETIME VARCHAR2(20)
VARIABLE INTERVAL NUMBER

BEGIN
SELECT DBID,BID,EID,
       TO_CHAR(BEGIN_INTERVAL_TIME,'YYYY/MM/DD HH24:MI:SS') BTIME,
       TO_CHAR(END_INTERVAL_TIME  ,'YYYY/MM/DD HH24:MI:SS') ETIME,
       EXTRACT(SECOND   FROM END_INTERVAL_TIME - BEGIN_INTERVAL_TIME) 
       + EXTRACT(MINUTE FROM END_INTERVAL_TIME - BEGIN_INTERVAL_TIME) * 60
       + EXTRACT(HOUR   FROM END_INTERVAL_TIME - BEGIN_INTERVAL_TIME) * 3600
       + EXTRACT(DAY    FROM END_INTERVAL_TIME - BEGIN_INTERVAL_TIME) * 86400 as "INTERVAL"
 INTO :DBID,:BID,:EID,:BTIME,:ETIME,:INTERVAL
  FROM (SELECT DISTINCT DBID,LAG(SNAP_ID) OVER(ORDER BY SNAP_ID) BID,SNAP_ID EID,
               MAX(BEGIN_INTERVAL_TIME) AS "BEGIN_INTERVAL_TIME",
               MAX(END_INTERVAL_TIME) AS "END_INTERVAL_TIME"
          FROM DBA_HIST_SNAPSHOT
         GROUP BY DBID,SNAP_ID
         ORDER BY SNAP_ID DESC)
 WHERE ROWNUM = 1;
END;
/

SELECT :ETIME AS "DATE",INSTANCE_NUMBER INST_ID,'Host Mem' AS "NAME",VALUE
  FROM DBA_HIST_OSSTAT
 WHERE SNAP_ID = :EID
   AND STAT_NAME='PHYSICAL_MEMORY_BYTES'
UNION
SELECT :ETIME,INSTANCE_NUMBER INST_ID,'PGA use',VALUE NEPGAALLOC 
  FROM DBA_HIST_PGASTAT
 WHERE SNAP_ID = :EID
   AND DBID = :DBID 
   AND NAME = 'total PGA allocated'
UNION 
SELECT :ETIME,MT.INST_ID,'SGA use',
        CASE WHEN MT.NESGATRGT IS NOT NULL AND MT.NESGATRGT <> 0 THEN MT.NESGATRGT ELSE SGA.NESGAALLOC END NESGAALLOC 
  FROM (SELECT INSTANCE_NUMBER INST_ID,CURRENT_SIZE NESGATRGT
          FROM DBA_HIST_MEM_DYNAMIC_COMP
         WHERE DBID = :DBID
           AND COMPONENT = 'SGA Target'
           AND SNAP_ID = :EID) MT ,
       (SELECT INSTANCE_NUMBER INST_ID, SUM(VALUE) NESGAALLOC
          FROM DBA_HIST_SGA 
         WHERE DBID = :DBID
           AND SNAP_ID = :EID
           GROUP BY  INSTANCE_NUMBER) SGA
 WHERE MT.INST_ID = SGA.INST_ID
 ORDER BY 2,4 DESC;
