SELECT 
    TABLESPACE_NAME AS NAME, 
    ROUND(NVL((CURRENT_BLOCKS-FREE_TOTAL_BLOCKS) / TOTAL_BLOCKS * 100,100),1) USAGE
FROM
  ( SELECT TABLESPACE_NAME, SUM(CASE WHEN MAXBLOCKS>0 THEN MAXBLOCKS ELSE BLOCKS END) TOTAL_BLOCKS
    FROM DBA_DATA_FILES
    GROUP BY TABLESPACE_NAME),
  ( SELECT TABLESPACE_NAME CURRENT_TABLESPACE_NAME, SUM(BLOCKS) CURRENT_BLOCKS
    FROM DBA_DATA_FILES
    GROUP BY TABLESPACE_NAME),
  ( SELECT TABLESPACE_NAME FREE_TABLESPACE_NAME,
      NVL(SUM(BLOCKS),0) FREE_TOTAL_BLOCKS
    FROM DBA_FREE_SPACE
    GROUP BY TABLESPACE_NAME)
   WHERE TABLESPACE_NAME = FREE_TABLESPACE_NAME(+)
     AND TABLESPACE_NAME = CURRENT_TABLESPACE_NAME
UNION ALL
SELECT 
    S.TABLESPACE_NAME NAME,
    ROUND((S.TOT_USED_BLOCKS/F.TOTAL_BLOCKS)*100,1) USAGE
FROM (SELECT TABLESPACE_NAME,SUM(USED_BLOCKS) TOT_USED_BLOCKS FROM V$SORT_SEGMENT 
        WHERE TABLESPACE_NAME IN ( SELECT TABLESPACE_NAME FROM DBA_TABLESPACES WHERE CONTENTS='TEMPORARY' )
        GROUP BY TABLESPACE_NAME) S,
         (SELECT TABLESPACE_NAME, SUM(BLOCKS) TOTAL_BLOCKS FROM DBA_TEMP_FILES 
        WHERE TABLESPACE_NAME IN ( SELECT TABLESPACE_NAME FROM DBA_TABLESPACES WHERE CONTENTS='TEMPORARY' )
        GROUP BY TABLESPACE_NAME) F
    WHERE S.TABLESPACE_NAME=F.TABLESPACE_NAME;

