
select
 a.END_TIME,
 b.OWNER,
 DECODE(b.SUBOBJECT_NAME,NULL,b.OBJECT_NAME,b.OBJECT_NAME||'('||b.SUBOBJECT_NAME||')') segment_name,
 b.OBJECT_TYPE,
 c.BUFFER_POOL,
 c.bytes,
 a.LOGICAL_READS,
 a.PHYSICAL_READS
from
(select * from 
(select
 a.START_ID,
 a.END_ID,
 a.END_TIME,
 a.DATAOBJ#,
 a.OBJ#,
 a.TS#,
 a.LOGICAL_READS,
 a.BUFFER_BUSY_WAITS,
 a.DB_BLOCK_CHANGES,
 a.PHYSICAL_READS,
 a.PHYSICAL_WRITES,
 a.DIRECT_PHYSICAL_READS,
 a.DIRECT_PHYSICAL_WRITES,
 a.ITL_WAITS,
 a.ROW_LOCK_WAITS
from
(SELECT
 LAG(a.SNAP_ID, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as START_ID,
 a.SNAP_ID END_ID,
 to_char(b.SNAP_TIME,'YYYY/MM/DD HH24:MI:SS') END_TIME,
 a.DATAOBJ#,
 a.OBJ#,
 a.TS#,
 a.LOGICAL_READS - LAG(a.LOGICAL_READS, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as LOGICAL_READS,
 a.BUFFER_BUSY_WAITS - LAG(a.BUFFER_BUSY_WAITS, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as BUFFER_BUSY_WAITS,
 a.DB_BLOCK_CHANGES - LAG(a.DB_BLOCK_CHANGES, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as DB_BLOCK_CHANGES,
 a.PHYSICAL_READS - LAG(a.PHYSICAL_READS, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as PHYSICAL_READS,
 a.PHYSICAL_WRITES - LAG(a.PHYSICAL_WRITES, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as PHYSICAL_WRITES,
 a.DIRECT_PHYSICAL_READS - LAG(a.DIRECT_PHYSICAL_READS, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as DIRECT_PHYSICAL_READS,
 a.DIRECT_PHYSICAL_WRITES - LAG(a.DIRECT_PHYSICAL_WRITES, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as DIRECT_PHYSICAL_WRITES,
 a.ITL_WAITS - LAG(a.ITL_WAITS, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as ITL_WAITS,
 a.ROW_LOCK_WAITS - LAG(a.ROW_LOCK_WAITS, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as ROW_LOCK_WAITS
 FROM stats$seg_stat a,STATS$SNAPSHOT b
WHERE a.SNAP_ID = b.SNAP_ID
  AND b.SNAP_LEVEL = 7) a
where a.LOGICAL_READS >= 0
  and a.BUFFER_BUSY_WAITS >= 0
  and a.DB_BLOCK_CHANGES >= 0
  and a.PHYSICAL_READS >= 0
  and a.PHYSICAL_WRITES >= 0
  and a.DIRECT_PHYSICAL_READS >= 0
  and a.DIRECT_PHYSICAL_WRITES >= 0
  and a.ITL_WAITS >= 0
  and a.ROW_LOCK_WAITS >=0
  and a.END_ID - a.START_ID = 7
  and a.END_ID = &ENDSNAP_ID
 order by  a.LOGICAL_READS DESC)
where rownum < 101
union
select * from 
(select
 a.START_ID,
 a.END_ID,
 a.END_TIME,
 a.DATAOBJ#,
 a.OBJ#,
 a.TS#,
 a.LOGICAL_READS,
 a.BUFFER_BUSY_WAITS,
 a.DB_BLOCK_CHANGES,
 a.PHYSICAL_READS,
 a.PHYSICAL_WRITES,
 a.DIRECT_PHYSICAL_READS,
 a.DIRECT_PHYSICAL_WRITES,
 a.ITL_WAITS,
 a.ROW_LOCK_WAITS
from
(SELECT
 LAG(a.SNAP_ID, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as START_ID,
 a.SNAP_ID END_ID,
 to_char(b.SNAP_TIME,'YYYY/MM/DD HH24:MI:SS') END_TIME,
 a.DATAOBJ#,
 a.OBJ#,
 a.TS#,
 a.LOGICAL_READS - LAG(a.LOGICAL_READS, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as LOGICAL_READS,
 a.BUFFER_BUSY_WAITS - LAG(a.BUFFER_BUSY_WAITS, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as BUFFER_BUSY_WAITS,
 a.DB_BLOCK_CHANGES - LAG(a.DB_BLOCK_CHANGES, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as DB_BLOCK_CHANGES,
 a.PHYSICAL_READS - LAG(a.PHYSICAL_READS, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as PHYSICAL_READS,
 a.PHYSICAL_WRITES - LAG(a.PHYSICAL_WRITES, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as PHYSICAL_WRITES,
 a.DIRECT_PHYSICAL_READS - LAG(a.DIRECT_PHYSICAL_READS, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as DIRECT_PHYSICAL_READS,
 a.DIRECT_PHYSICAL_WRITES - LAG(a.DIRECT_PHYSICAL_WRITES, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as DIRECT_PHYSICAL_WRITES,
 a.ITL_WAITS - LAG(a.ITL_WAITS, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as ITL_WAITS,
 a.ROW_LOCK_WAITS - LAG(a.ROW_LOCK_WAITS, 1) OVER (partition by a.DATAOBJ#,OBJ#,TS# ORDER BY a.DATAOBJ#,OBJ#,TS#,a.SNAP_ID) as ROW_LOCK_WAITS
 FROM stats$seg_stat a,STATS$SNAPSHOT b
WHERE a.SNAP_ID = b.SNAP_ID
  AND b.SNAP_LEVEL = 7) a
where a.LOGICAL_READS >= 0
  and a.BUFFER_BUSY_WAITS >= 0
  and a.DB_BLOCK_CHANGES >= 0
  and a.PHYSICAL_READS >= 0
  and a.PHYSICAL_WRITES >= 0
  and a.DIRECT_PHYSICAL_READS >= 0
  and a.DIRECT_PHYSICAL_WRITES >= 0
  and a.ITL_WAITS >= 0
  and a.ROW_LOCK_WAITS >=0
  and a.END_ID - a.START_ID = 7
  and a.END_ID = &ENDSNAP_ID
 order by  a.PHYSICAL_READS DESC)
where rownum < 101) a,stats$seg_stat_obj b,dba_segments c
where a.dataobj# = b.dataobj#
  and a.obj#     = b.obj#
  and b.object_name = c.segment_name
  and b.owner = c.owner
  and b.object_type = c.segment_type
  and nvl(b.SUBOBJECT_NAME,' ') = nvl(c.PARTITION_NAME,' ')
  and b.owner not in ('SYS','SYSTEM','PERFSTAT')
order by a.PHYSICAL_READS DESC
;
