SELECT
  TO_CHAR(SYSDATE,'YYYY/MM/DD HH24:MI:SS') AS "DATE",
  (SELECT NAME FROM V$DATABASE) AS "SERVICE_NAME",
  NAME AS "DISKGROUP_NAME",
  TYPE,
  TOTAL_MB/1024 "TOTAL(GB)",
  (TOTAL_MB-FREE_MB)/1024 "USED(GB)",
  FREE_MB/1024 "FREE(GB)",
  ((TOTAL_MB-FREE_MB)/TOTAL_MB*100) "USED(%)"
FROM V$ASM_DISKGROUP
WHERE STATE = 'CONNECTED'
ORDER BY NAME
;

