col "TIME(s)" format 999,999,999,990.999
col WAIT_CLASS format a20

select a.INSTANCE_NUMBER,to_char(b.SNAP_TIME,'YYYY/MM/DD HH24:MI:SS'),a.WAIT_CLASS,a.time AS "TIME(s)" from
(select a.INSTANCE_NUMBER,a.START_ID,a.END_ID,b.WAIT_CLASS,sum(a."VALUE")/1000000 AS time from
(select
 a.INSTANCE_NUMBER,
 LAG(a.SNAP_ID, 1) OVER (partition by a.INSTANCE_NUMBER,a.EVENT ORDER BY a.INSTANCE_NUMBER,a.EVENT,a.SNAP_ID) as START_ID,
 a.SNAP_ID END_ID,
 a.EVENT,a.EVENT_ID,
CASE WHEN a.TIME_WAITED_MICRO - LAG(a.TIME_WAITED_MICRO, 1) OVER (partition by a.INSTANCE_NUMBER,a.EVENT ORDER BY a.INSTANCE_NUMBER,a.EVENT,a.SNAP_ID)<'0'
     THEN 0
     ELSE a.TIME_WAITED_MICRO - LAG(a.TIME_WAITED_MICRO, 1) OVER (partition by a.INSTANCE_NUMBER,a.EVENT ORDER BY a.INSTANCE_NUMBER,a.EVENT,a.SNAP_ID)
END "VALUE"
 from STATS$SYSTEM_EVENT a, STATS$SNAPSHOT b
where a.SNAP_ID = b.SNAP_ID
  and a.INSTANCE_NUMBER = b.INSTANCE_NUMBER
  and b.SNAP_LEVEL = 0) a,v$event_name b
  where a.EVENT_ID = b.EVENT_ID
    and b.WAIT_CLASS <> 'Idle'
  group by a.INSTANCE_NUMBER,a.START_ID,a.END_ID,b.WAIT_CLASS 
UNION
select
 a.INSTANCE_NUMBER,
 LAG(a.SNAP_ID, 1) OVER (partition by  a.INSTANCE_NUMBER,a.NAME ORDER BY  a.INSTANCE_NUMBER,a.NAME,a.SNAP_ID ) as START_ID,
 a.SNAP_ID END_ID,
 'CPU TIME' "NAME",
CASE WHEN a.VALUE*10000 - LAG(a.VALUE*10000, 1) OVER (partition by  a.INSTANCE_NUMBER,a.NAME ORDER BY  a.INSTANCE_NUMBER,a.NAME,a.SNAP_ID)<'0'
     THEN 0
     ELSE a.VALUE*10000 - LAG(a.VALUE*10000, 1) OVER (partition by  a.INSTANCE_NUMBER,a.NAME ORDER BY  a.INSTANCE_NUMBER,a.NAME,a.SNAP_ID)
END "VALUE"
from STATS$SYSSTAT a,STATS$SNAPSHOT b
where a.SNAP_ID = b.SNAP_ID
  and a.INSTANCE_NUMBER = b.INSTANCE_NUMBER
  and b.SNAP_LEVEL = 0
  and a.name = 'CPU used by this session') a, STATS$SNAPSHOT b
where a.END_ID = b.SNAP_ID
  and a.INSTANCE_NUMBER = b.INSTANCE_NUMBER
  and b.SNAP_LEVEL = 0
  and b.SNAP_ID = (select max(snap_id) from STATS$SNAPSHOT)
  order by 1,2,3;

