SELECT TO_CHAR("DATE",'YYYY/MM/DD HH24:MI:SS') AS "DATE",
       PLAN_HASH_VALUE,
       SQL_COUNT,
       SUM_SHARABLE_MEM,
       SUM_VERSION_COUNT,
       SUM_SQL_LENGTH,
       AVG_SQL_LENGTH
  FROM SHARED_POOL_USED_HIST
 WHERE "DATE" = (SELECT MAX("DATE") FROM SHARED_POOL_USED_HIST)
 ORDER BY 4 DESC;
