COL VALUE FORMAT 999,999,999,999,999
COL DATE FORMAT A19

VARIABLE DBID NUMBER
VARIABLE BID NUMBER
VARIABLE EID NUMBER
VARIABLE BTIME VARCHAR2(20)
VARIABLE ETIME VARCHAR2(20)
VARIABLE INTERVAL NUMBER


BEGIN
SELECT DBID,BID,EID,BTIME,ETIME,INTERVAL INTO :DBID,:BID,:EID,:BTIME,:ETIME,:INTERVAL
  FROM (SELECT DBID,LAG(SNAP_ID) OVER(ORDER BY STARTUP_TIME,SNAP_ID) BID,SNAP_ID EID,
               TO_CHAR(LAG(SNAP_TIME) OVER(ORDER BY STARTUP_TIME,SNAP_ID),'YYYY/MM/DD HH24:MI:SS') BTIME,
               TO_CHAR(SNAP_TIME,'YYYY/MM/DD HH24:MI:SS') ETIME,
               (SNAP_TIME - LAG(SNAP_TIME) OVER(ORDER BY STARTUP_TIME,SNAP_ID))*(24*3600) "INTERVAL"
          FROM STATS$SNAPSHOT
         ORDER BY STARTUP_TIME DESC,SNAP_ID DESC)
 WHERE ROWNUM = 1;
END;
/

SELECT :ETIME AS "DATE",INSTANCE_NUMBER INST_ID,'Host Mem' AS "NAME",VALUE
FROM STATS$OSSTAT
WHERE SNAP_ID = :EID
AND OSSTAT_ID = 1008
UNION
SELECT :ETIME,INSTANCE_NUMBER INST_ID,'PGA use',VALUE NEPGAALLOC
FROM STATS$PGASTAT
WHERE SNAP_ID = :EID
AND DBID = :DBID
AND NAME = 'total PGA allocated'
UNION
SELECT :ETIME,MT.INST_ID,'SGA use',
CASE WHEN MT.NESGATRGT IS NOT NULL AND MT.NESGATRGT <> 0 THEN MT.NESGATRGT ELSE SGA.NESGAALLOC END NESGAALLOC
FROM (SELECT INSTANCE_NUMBER INST_ID,CURRENT_SIZE NESGATRGT
FROM STATS$MEMORY_DYNAMIC_COMPS
WHERE DBID = :DBID
AND COMPONENT = 'SGA Target'
AND SNAP_ID = :EID) MT ,
(SELECT INSTANCE_NUMBER INST_ID, SUM(VALUE) NESGAALLOC
FROM STATS$SGA
WHERE DBID = :DBID
AND SNAP_ID = :EID
GROUP BY  INSTANCE_NUMBER) SGA
WHERE MT.INST_ID = SGA.INST_ID
ORDER BY 2,4 DESC;
