SELECT
	STATISTIC_NAME, TH, COUNT
FROM (
	SELECT STATISTIC_NAME, 0 TH,      COUNT(*) COUNT FROM V$SEGSTAT WHERE VALUE > 0      GROUP BY STATISTIC_NAME
	UNION ALL
	SELECT STATISTIC_NAME, 100 TH,    COUNT(*) COUNT FROM V$SEGSTAT WHERE VALUE > 100    GROUP BY STATISTIC_NAME
	UNION ALL
	SELECT STATISTIC_NAME, 1000 TH,   COUNT(*) COUNT FROM V$SEGSTAT WHERE VALUE > 1000   GROUP BY STATISTIC_NAME
	UNION ALL
	SELECT STATISTIC_NAME, 10000 TH,  COUNT(*) COUNT FROM V$SEGSTAT WHERE VALUE > 10000  GROUP BY STATISTIC_NAME
	UNION ALL
	SELECT STATISTIC_NAME, 100000 TH, COUNT(*) COUNT FROM V$SEGSTAT WHERE VALUE > 100000 GROUP BY STATISTIC_NAME
)
WHERE STATISTIC_NAME IN ('logical reads', 'physical reads', 'buffer busy waits', 'row lock waits', 'ITL waits')
ORDER BY STATISTIC_NAME,TH
;
