SELECT 
	STMTID, 
	TO_CHAR(LAST_METRICS_UPDATE, 'YYYY-MM-DD HH24:MI:SS') AS LAST_METRICS_UPDATE,
	STMT_TEXT
FROM 
	TABLE(MON_GET_PKG_CACHE_STMT( NULL, NULL, NULL, -2))
WHERE 
	NUM_EXEC_WITH_METRICS <> 0;

