#!/bin/bash
#
# Node configuration 
#
# Usage : nodeconfig
#         --add {node_path} [--ip=s] [--user=s] [--pass=s]
#         --rex {node_path} {command}

LANG=C;export LANG
CWD=`dirname $0`
CMDNAME=`basename $0`

CWD=`dirname $0`
export SITEHOME="$(git rev-parse --show-toplevel)"

if [ ! -d "$SITEHOME/lib/Getperf/Command/Site" -o ! -d "$SITEHOME/node" ]; then
	echo "Invalid site home directory '$SITEHOME'"
	exit -1
fi

perl -I$SITEHOME/lib $CWD/nodeconfig.pl $*
